name: Pull and Restart the Server

on:
  push:
    branches: [ "master" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/ksairos/Projects/korean_learning_bot
    steps:
      - name: Pull and rebase the project
        run: |
          git pull --rebase

      - name: Make scripts executable
        run: |
          chmod +x ./stop_all.sh
          chmod +x ./start_all.sh

      - name: Run the script
        run: ./stop_all.sh

      - name: Run the script
        run: ./start_all.sh